### PR TITLE
Add test functions to test the UA's interaction with the requestDevic…

### PR DESCRIPTION
**Pull request by jyasskin**
Here are the functions from https://codereview.chromium.org/1325953002/, with some renamings.

@scheib @g-ortuno @yrliou, what do you think? `getBluetoothManualChooserEvents()` is implemented with a synchronous IPC in Chromium (bad for the web; probably ok for tests). I could switch it to return a Promise, but that would increase the implementation complexity.

### CODE REVIEW

**Comment by scheib** [comment]
Documenting the methods here LGTM. The sync IPC is OK for testing only, though it may not be so very much extra work to make that promise/async based?

**Comment by jyasskin** [comment]
It looks like a fair amount of work in Chromium: In [components/test_runner/test_runner.cc](https://code.google.com/p/chromium/codesearch/#chromium/src/components/test_runner/test_runner.cc&l=363) we don't have access to the [Blink methods for creating Promises](https://code.google.com/p/chromium/codesearch/#chromium/src/third_party/WebKit/Source/bindings/core/v8/ScriptPromiseResolver.h), so we'd need to use V8 directly. Gin also provides no support. The `IdMap` or queue of in-flight requests and the extra IPC definition aren't huge problems, but they're more complex than not having them. Finally, the blocking nature reduces the amount of spinning we have to do when using `getBluetoothManualChooserEvents()` to wait for the next event to arrive.

I've added a note about why the function doesn't return a Promise.

**Comment by jyasskin** [comment]
The demo for this is at https://rawgit.com/jyasskin/web-bluetooth-1/chooser-test-apis/tests/index.html.

**Comment by jyasskin** [comment]
Merged to main branch.

**Pull request closed without merging**
